### ISSUE TITLE
Program is running wrong

### ISSUE THREAD

**Issue by Carlos2181** [khazali/Starfish#1]
It's a great architecture to solve the flow simulation problem. However，I tried to run the program in Windows 10 platform, but the display doesn't work and prompted the missing file（impi.dll; libiomp5md.dll). Can you give me some advice?

**Comment by khazali** [comment]
Have you compiled the code? The included executable has built for windows 7x64 using Intel 2018u3 toolchain; which may not be the case for you.

**Comment by Carlos2181** [comment]
ok，thank you for  your advice.
