### ISSUE TITLE
Absolute permeability and Capillary pressure matches for WW Berea

### ISSUE THREAD

**Issue by parsegov** [khazali/Starfish#3]
Have you modified radii of pores and throats of Berea pore network (Dong and Blunt (2009)) to match rel perms?  In your output files for WW Berea test case (Berea_Drainage.dat and Berea_Imbibition.dat), absolute Permeability is reported as 3107.1 [mD?]. Meanwhile, Dong has reported ~1,100 [mD]. 

What is your porosity for Berea case? 

Could you please provide other inputs for Starfish (in addition to Berea_fluid.dat) similar to PoreFlow keywords (SAT_TARGET, PORE_FILL_ALG,...)? 

As I understand from Berea_fluid.dat and Table 1:

Densities = 1000 and 1000 [kg/m3]
IFT = 0.030 [N/m]
CA in rads = 0.87266462599716478846184538424431 (intrinsic) 1.0471975511965977461542144610932 (adancing)?

Could you please explain what these two controls (0.00089 0.00164) stand for? Viscosities in [Pa.s]? But they should be 0.00105 Pa.s (water) and 0.00139 Pa.s (oil), respectively, as mentioned in Table 1.

Have you modeled equal CA for all pores, or assigned some CA distribution?

Is your Pc in [Pa]? 

Have you compared your results with those of Valvante (2004) http://www.imperial.ac.uk/earth-science/research/research-groups/perm/research/pore-scale-modelling/software/two-phase-network-modelling-code/?

**Comment by khazali** [comment]
From the first to last:
-No, and I think Starfish calculations matched the PoreFlow software from Imperial College.
-Starfish cannot calculate it, but adding it to the code is super easy.
-It would be good to have them. However, we have some other priorities in developing Starfish. For the time being, we are working on making Starfish compositional.
-All correct, however, the first contact angle is the receding one.
-They are viscosities. The viscosity of fluid must not affect our calculation of absolute and relative permeabilities.
-CAs are constant during the drainage and dynamic in the imbibition stage.
-Yes.
-I think they matched.
